import { createElement } from '@lwc/engine-dom';
import BC_S4_06_RequestCRUD from 'c/bC_S4_06_RequestCRUD';

describe('c-b-c-s-4-06-request-crud', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-b-c-s-4-06-request-crud', {
            is: BC_S4_06_RequestCRUD
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});